#!/usr/bin/env node
/**
 * escala-standards-sync — copy always-on rules from this package into the
 * consuming project's .clinerules/.
 *
 * Run from a project that has escala-dev-standards as a devDependency:
 *   npx escala-standards-sync
 *
 * Rule selection (optional) in the consumer's package.json:
 *   "escalaStandards": { "rules": ["engineering-foundations", "backend-nestjs", ...] }
 * Default: ALL rules (full + pointers).
 *
 * Managed-file safety: only files carrying the generated marker are overwritten
 * or removed; hand-written .clinerules files are never touched.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync, unlinkSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const MARKER = 'Generated by scripts/build.sh';
const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const rulesDir = join(pkgRoot, 'dist', 'clinerules');
const projectRoot = process.env.INIT_CWD || process.cwd();
const target = join(projectRoot, '.clinerules');

if (!existsSync(rulesDir)) {
  console.error(`escala-standards-sync: no dist/clinerules found at ${rulesDir}. Run the package build.`);
  process.exit(1);
}

let wanted = null; // null => all
try {
  const consumerPkg = JSON.parse(readFileSync(join(projectRoot, 'package.json'), 'utf8'));
  if (Array.isArray(consumerPkg?.escalaStandards?.rules)) wanted = consumerPkg.escalaStandards.rules;
} catch { /* no consumer package.json — sync everything */ }

mkdirSync(target, { recursive: true });

const available = readdirSync(rulesDir).filter((f) => f.endsWith('.md'));
const selected = wanted ? available.filter((f) => wanted.includes(f.replace(/\.md$/, ''))) : available;

let copied = 0;
for (const file of selected) {
  writeFileSync(join(target, file), readFileSync(join(rulesDir, file)));
  console.log(`  synced: .clinerules/${file}`);
  copied++;
}

// Remove previously-managed rules that are no longer selected (marker-guarded)
for (const file of readdirSync(target).filter((f) => f.endsWith('.md'))) {
  if (selected.includes(file)) continue;
  const content = readFileSync(join(target, file), 'utf8');
  if (content.includes(MARKER)) {
    unlinkSync(join(target, file));
    console.log(`  removed (deselected managed rule): .clinerules/${file}`);
  }
}

if (wanted) {
  for (const name of wanted) {
    if (!available.includes(`${name}.md`)) console.warn(`  WARN: unknown rule "${name}" in escalaStandards.rules`);
  }
}
console.log(`\nDone. ${copied} rule file(s) in ${target}`);
console.log('Hand-written .clinerules files were left untouched.');
