#!/usr/bin/env bash
# build.sh — generate dist/clinerules/*.md from src/.
# src/ is the canonical SKILL.md tree (consumed directly by the skills CLI);
# dist/ holds ONLY the flattened always-on Cline rules.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${REPO_ROOT}/src"
DIST="${REPO_ROOT}/dist"
POINTER_SKILLS=" database-prisma infra-deploy-gcp battle-tested-patterns "

strip_frontmatter() {
  awk 'NR==1 && /^---[[:space:]]*$/ {infm=1; next}
       infm && /^---[[:space:]]*$/ {infm=0; next}
       !infm {print}' "$1"
}
get_meta() {
  awk -v k="$2" 'NR==1 && /^---/ {infm=1; next}
       infm && /^---/ {exit}
       infm { if ($0 ~ "^"k":") { sub("^"k":[[:space:]]*",""); print; exit } }' "$1"
}

rm -rf "${DIST}"
mkdir -p "${DIST}/clinerules"

for skilldir in "${SRC}"/*/; do
  skill="$(basename "${skilldir}")"
  skillmd="${skilldir}SKILL.md"
  [ -f "${skillmd}" ] || { echo "WARN: ${skill} has no SKILL.md, skipping"; continue; }

  out="${DIST}/clinerules/${skill}.md"
  name="$(get_meta "${skillmd}" name)"; name="${name:-$skill}"
  printf '<!-- Generated by scripts/build.sh — do not edit. Source: src/%s -->\n\n' "${skill}" > "${out}"

  if [[ "${POINTER_SKILLS}" == *" ${skill} "* ]]; then
    desc="$(get_meta "${skillmd}" description)"
    printf '# %s (on-demand)\n\n%s\n\n' "${name}" "${desc}" >> "${out}"
    printf '> Pointer only. Load the full skill on demand: `npx skills add colivares82/escala-dev-standards`\n' >> "${out}"
    printf '> or read `src/%s/SKILL.md` (+ references/) in the standards package when this topic is in play.\n' "${skill}" >> "${out}"
  else
    strip_frontmatter "${skillmd}" >> "${out}"
    if [ -d "${skilldir}references" ]; then
      for ref in "${skilldir}references"/*.md; do
        [ -e "${ref}" ] || continue
        printf '\n---\n\n## Reference: %s\n\n' "$(basename "${ref}")" >> "${out}"
        cat "${ref}" >> "${out}"
      done
    fi
  fi
  echo "built: ${skill}"
done
echo ""
echo "dist/clinerules: $(ls -1 "${DIST}/clinerules" | wc -l | tr -d ' ') files"
