#!/usr/bin/env node
/**
 * escala-standards-sync — populate a consuming project with BOTH channels from this package:
 *
 *   dist/clinerules/*.md  →  <project>/.clinerules/          (always-on rules, Cline auto-loads)
 *   src/<skill>/          →  <project>/.cline/skills/<skill>/ (on-demand skills, Cline auto-detects)
 *
 * Run from a project that has escala-dev-standards as a devDependency:
 *   npx escala-standards-sync        (or wire it to "postinstall")
 *
 * Selection (optional) in the consumer's package.json — default is ALL:
 *   "escalaStandards": {
 *     "rules":  ["engineering-foundations", "backend-nestjs", ...],
 *     "skills": ["battle-tested-patterns", ...]
 *   }
 *
 * Managed-content safety:
 *   - Rules: only files containing the generated marker are overwritten/removed.
 *   - Skills: only directories containing a .escala-managed marker file are
 *     overwritten/removed. Third-party skills and hand-written rules are never touched.
 */
import {
  readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync, unlinkSync,
  rmSync, cpSync, statSync,
} from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const RULE_MARKER = 'Generated by scripts/build.sh';
const SKILL_MARKER = '.escala-managed';

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const rulesSrc = join(pkgRoot, 'dist', 'clinerules');
const skillsSrc = join(pkgRoot, 'src');
const projectRoot = process.env.INIT_CWD || process.cwd();

let cfg = {};
try {
  const pkg = JSON.parse(readFileSync(join(projectRoot, 'package.json'), 'utf8'));
  cfg = pkg.escalaStandards ?? {};
} catch { /* no consumer package.json — sync everything */ }

/* ── Channel A: always-on rules → .clinerules/ ─────────────────────────── */
const rulesTarget = join(projectRoot, '.clinerules');
mkdirSync(rulesTarget, { recursive: true });

const availableRules = existsSync(rulesSrc)
  ? readdirSync(rulesSrc).filter((f) => f.endsWith('.md'))
  : [];
const selectedRules = Array.isArray(cfg.rules)
  ? availableRules.filter((f) => cfg.rules.includes(f.replace(/\.md$/, '')))
  : availableRules;

let rulesCopied = 0;
for (const file of selectedRules) {
  writeFileSync(join(rulesTarget, file), readFileSync(join(rulesSrc, file)));
  console.log(`  rule  synced: .clinerules/${file}`);
  rulesCopied++;
}
for (const file of readdirSync(rulesTarget).filter((f) => f.endsWith('.md'))) {
  if (selectedRules.includes(file)) continue;
  if (readFileSync(join(rulesTarget, file), 'utf8').includes(RULE_MARKER)) {
    unlinkSync(join(rulesTarget, file));
    console.log(`  rule  removed (deselected): .clinerules/${file}`);
  }
}

/* ── Channel B: on-demand skills → .cline/skills/ ──────────────────────── */
const skillsTarget = join(projectRoot, '.cline', 'skills');
mkdirSync(skillsTarget, { recursive: true });

const availableSkills = readdirSync(skillsSrc).filter((d) => {
  const p = join(skillsSrc, d);
  return statSync(p).isDirectory() && existsSync(join(p, 'SKILL.md'));
});
const selectedSkills = Array.isArray(cfg.skills)
  ? availableSkills.filter((s) => cfg.skills.includes(s))
  : availableSkills;

let skillsCopied = 0;
for (const skill of selectedSkills) {
  const dest = join(skillsTarget, skill);
  if (existsSync(dest)) {
    // Never clobber a directory we don't manage (e.g. a third-party skill of the same name)
    if (!existsSync(join(dest, SKILL_MARKER))) {
      console.warn(`  skill SKIPPED (unmanaged dir already exists): .cline/skills/${skill}`);
      continue;
    }
    rmSync(dest, { recursive: true });
  }
  cpSync(join(skillsSrc, skill), dest, { recursive: true });
  writeFileSync(join(dest, SKILL_MARKER), 'Managed by escala-dev-standards. Do not edit; changes are overwritten on sync.\n');
  console.log(`  skill synced: .cline/skills/${skill}/`);
  skillsCopied++;
}
for (const dir of readdirSync(skillsTarget)) {
  const p = join(skillsTarget, dir);
  if (!statSync(p).isDirectory() || selectedSkills.includes(dir)) continue;
  if (existsSync(join(p, SKILL_MARKER))) {
    rmSync(p, { recursive: true });
    console.log(`  skill removed (deselected): .cline/skills/${dir}/`);
  }
}

/* ── Selection warnings + summary ──────────────────────────────────────── */
if (Array.isArray(cfg.rules)) {
  for (const n of cfg.rules) if (!availableRules.includes(`${n}.md`)) console.warn(`  WARN: unknown rule "${n}"`);
}
if (Array.isArray(cfg.skills)) {
  for (const n of cfg.skills) if (!availableSkills.includes(n)) console.warn(`  WARN: unknown skill "${n}"`);
}
console.log(`\nDone. ${rulesCopied} rule(s) → .clinerules/ · ${skillsCopied} skill(s) → .cline/skills/`);
console.log('Hand-written rules and third-party skills were left untouched.');
